#!/bin/bash
# Launch created by Amir Bagheri and edited by ehsan (@mafia_boy)
tgcli_version="171003-nightly"
luarocks_version=2.4.2
lualibs=(
'luasec'
'luarepl'
'lbase64 20120807-3'
'luafilesystem'
'lub'
'luaexpat'
'redis-lua'
'lua-cjson'
'fakeredis'
'xml'
'feedparser'
'serpent'
)

today=`date +%F`
install() {
sudo apt-get update 
sudo apt-get upgrade
sudo apt-get install git redis-server lua5.2 liblua5.2-dev lua-lgi libnotify-dev unzip tmux -y && add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update 
apt-get upgrade 
sudo do-release-upgrade
sudo apt-get install libconfig++9v5 libstdc++6 
sudo apt autoremove
sudo apt-get install gcc-4.9
sudo apt-get --yes install wget libconfig9 libjansson4 lua5.2 liblua5.2 make unzip git redis-server g++ whois fortune fortunes
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get install g++-4.7 -y c++-4.7 -y
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y
sudo apt-get install screen -y
sudo apt-get install tmux -y
sudo apt-get install libstdc++6 -y
sudo apt-get install lua-lgi -y
sudo apt-get install libnotify-dev -y
chmod +x bot
chmod +x tg
chmod +x autoenergy
}
get_sub() {
local flag=false c count cr=$'\r' nl=$'\n'
while IFS='' read -d '' -rn 1 c; do
 if $flag; then
 printf '%c' "$c"
  else
if [[ $c != $cr && $c != $nl ]]; then
  count=0
 else
((count++))
 if ((count > 1)); then
flag=true
fi
fi
fi
 done
}
make_progress() {
exe=`lua <<-EOF
    print(tonumber($1)/tonumber($2)*100)
EOF
`
    echo ${exe:0:4}
}
 get_tgcli_version() {
	echo "$tgcli_version"
}
 download_libs_lua() {
    if [[ ! -d "logs" ]]; then mkdir logs; fi
    if [[ -f "logs/logluarocks_${today}.txt" ]]; then rm logs/logluarocks_${today}.txt; fi
    local i
    for ((i=0;i<${#lualibs[@]};i++)); do
        printf "\r\33[2K"
        printf "\r• Installing Luarocks: wait... [`make_progress $(($i+1)) ${#lualibs[@]}`%%] [$(($i+1))/${#lualibs[@]}] ${lualibs[$i]}"
        ./.luarocks/bin/luarocks install ${lualibs[$i]} &>> logs/logluarocks_${today}.txt
    done
    sleep 0.2
sleep 0.2
printf "\n• Logfile created: $PWD/logs/logluarocks_${today}.txt\nDone\n"
rm -rf luarocks-2.2.2*
}
startbotlogo() {
sleep 0.5
clear
f=3 b=4
for j in f b; do
for i in {0..7}; do
printf -v $j$i %b "\e[${!j}${i}m"
done
done
echo -e "                \e[100m                                Bot Running                                \e[00;37;40m"

bld=$'\e[1m'
rst=$'\e[0m'
cat << EOF
 $f1  ▀▄   ▄▀     $f2 ▄▄▄████▄▄▄    $f3  ▄██▄     $f4  ▀▄   ▄▀     $f5 ▄▄▄████▄▄▄    $f6  ▄██▄  $rst
 $f1 ▄█▀███▀█▄    $f2███▀▀██▀▀███   $f3▄█▀██▀█▄   $f4 ▄█▀███▀█▄    $f5███▀▀██▀▀███   $f6▄█▀██▀█▄$rst
 $f1█▀███████▀█   $f2▀▀███▀▀███▀▀   $f3▀█▀██▀█▀   $f4█▀███████▀█   $f5▀▀███▀▀███▀▀   $f6▀█▀██▀█▀$rst
 $f1▀ ▀▄▄ ▄▄▀ ▀   $f2 ▀█▄ ▀▀ ▄█▀    $f3▀▄    ▄▀   $f4▀ ▀▄▄ ▄▄▀ ▀   $f5 ▀█▄ ▀▀ ▄█▀    $f6▀▄    ▄▀$rst
 
EOF
echo  "                          cerner persian launcher         "
echo "                            edited by MY_NAME_IS_EHSAN           "
echo ""
cat << EOF
 $bld$f1▄ ▀▄   ▄▀ ▄   $f2 ▄▄▄████▄▄▄    $f3  ▄██▄     $f4▄ ▀▄   ▄▀ ▄   $f5 ▄▄▄████▄▄▄    $f6  ▄██▄  $rst
 $bld$f1█▄█▀███▀█▄█   $f2███▀▀██▀▀███   $f3▄█▀██▀█▄   $f4█▄█▀███▀█▄█   $f5███▀▀██▀▀███   $f6▄█▀██▀█▄$rst
 $bld$f1▀█████████▀   $f2▀▀▀██▀▀██▀▀▀   $f3▀▀█▀▀█▀▀   $f4▀█████████▀   $f5▀▀▀██▀▀██▀▀▀   $f6▀▀█▀▀█▀▀$rst
 $bld$f1 ▄▀     ▀▄    $f2▄▄▀▀ ▀▀ ▀▀▄▄   $f3▄▀▄▀▀▄▀▄   $f4 ▄▀     ▀▄    $f5▄▄▀▀ ▀▀ ▀▀▄▄   $f6▄▀▄▀▀▄▀▄$rst
EOF
}
 config() {
    dir=$PWD
    wget http://luarocks.org/releases/luarocks-${luarocks_version}.tar.gz &>/dev/null
    tar zxpf luarocks-${luarocks_version}.tar.gz &>/dev/null
    cd luarocks-${luarocks_version}
    if [[ ${1} == "--no-null" ]]; then
        ./configure --prefix=$dir/.luarocks --sysconfdir=$dir/.luarocks/luarocks --force-config
        make bootstrap
    else
./configure --prefix=$dir/.luarocks --sysconfdir=$dir/.luarocks/luarocks --force-config &>/dev/null
make bootstrap &>/dev/null
fi
cd ..; rm -rf luarocks*
if [[ ${1} != "--no-download" ]]; then
download_libs_lua
wget --progress=bar:force https://valtman.name/files/telegram-bot-${tgcli_version}-linux 2>&1 | get_sub
mv telegram-bot-${tgcli_version}-linux tg; chmod +x tg
fi
for ((i=0;i<101;i++)); do
printf "\rConfiguring... [%i%%]" $i
sleep 0.007
done
mkdir $HOME/.telegram-bot; cat <<EOF > $HOME/.telegram-bot/config
default_profile = "main";
main = {
lua_script = "$HOME/energy_plus/bot/bot.lua";
};
EOF
printf "\nDone\n"
}
launch() {
./tg | grep -v "{"
}
resetlogin() {
 rm -rf $HOME/.telegram-bot
}
CerNer(){
mkdir $HOME/.telegram-bot; cat <<EOF > $HOME/.telegram-bot/config
default_profile = "main";
main = {
lua_script = "$HOME/energy_plus/bot/bot.lua";
};
EOF
printf "\nDone\n"
}
loginCli() {
./tg -p main --login --phone=${1}
} 
loginApi() {
./tg -p main --login --bot=${1}
}
function gitpull() {
git checkout energy  bot/ libs/
git pull
echo chmod +x energy | /bin/bash
version=$(echo "./energy tgcli_version" | /bin/bash)
updateTD $version
}
updateTD() {
wget --progress=bar:force https://valtman.name/files/telegram-bot-${1}-linux 2>&1 | get_sub
mv telegram-bot-${1}-linux tg; chmod +x tg
}
CONFIG() {
TXT=(
"درحال نصب لواروکس و پیکربندی "
)
printf "${TXT}"
printf "\n"
}
warning() {
TXT=(
"دستور وارد شده صحیح نیست !  لطفا از \n./energy help استفاده کنید!"
)
printf "${TXT}"
printf "\n"
}
case $1 in
config)
CONFIG
config ${2}
exit ;;
login-Cli)
echo "لطفا شماره خود را بدون  فاصله وارد کنید"
read phone_number
loginCli ${phone_number}
echo 'عملیات  انجام شد !'
exit;;
login-Api)
echo "لطفا توکن ربات خود را ارسال کنید !"
read TOKEN
loginApi ${TOKEN}
echo 'عملیات  انجام شد !'
exit;;
Change-Login)
echo 'عملیات درحال انجام'
sleep 1
resetlogin
CerNer
echo 'عملیات  انجام شد !'
exit;;
install)
install
exit;;
start)
startbotlogo
launch
exit;;
update)
gitpull
updateTD
exit ;;
tgcli_version)
get_tgcli_version
exit ;;
help)
echo "راهنمای اجرای سورس کرنر :  ••  "
echo "install -  نصب پکیج های مورد نیاز • "
echo "config - پیکربندی ودانلود  تیجی • "
echo "start - راه اندازی ربات   • "
echo "Change-Login - تغغیر حالت ربات    • "
echo "login-Cli - لوگین شدن به عنوان ربات cli "
echo "login-Api - لوگین شدن به عنوان ربات Api "
echo "update - اپدیت سورس • "
echo "help - راهنما • "
exit ;;
esac
warning
exit 0
 
